# OpenSearch Configuration
opensearch:
  host: "localhost"
  port: 9200
  use_ssl: false
  verify_certs: false
  # username: "admin"
  # password: "admin"
  index_name: "chatbi_autocomplete"
  
# Redis Configuration (for user behavior tracking)
redis:
  host: "localhost"
  port: 6379
  db: 0
  
# Autocomplete Configuration
autocomplete:
  max_suggestions: 10
  min_score: 0.1
  keyword_weight: 0.7
  vector_weight: 0.3
  personalization_weight: 0.2
  enable_personalization: true
  enable_prefix_preservation: true  # Enable intelligent prefix-preserving completion for long queries
  
# Vector Model Configuration
vector_model:
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  dimension: 384
  
# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  title: "ChatBI Autocomplete Service"
  description: "Intelligent autocomplete service with hybrid search and personalization"
  version: "1.0.0"

# LLM Configuration (optional - for enhanced recommendations)
llm:
  enabled: false  # Set to true to enable LLM features
  provider: "openai"  # Options: "openai", "anthropic", "local"
  model: "gpt-3.5-turbo"  # Model name
  temperature: 0.7  # Temperature for generation (0-1)
  max_tokens: 150  # Maximum tokens to generate
  # api_key: ""  # Set via environment variable: OPENAI_API_KEY or ANTHROPIC_API_KEY
